# Generated by Django 3.2.3 on 2021-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место отдыха', 'verbose_name_plural': 'Места отдыха'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Изображение места отдыха', 'verbose_name_plural': 'Изображение мест отдыха'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Сортировать'),
        ),
    ]
