# Generated by Django 3.2.3 on 2021-05-25 19:01

from django.db import migrations


def set_blanke(apps, schema_editor):
    Place = apps.get_model("places", "Place")
    for place in Place.objects.all():
        if place.description_short is None:
            place.description_short = ""
        if place.description_long is None:
            place.description_long = ""
        if place.latitude is None:
            place.latitude = ""
        if place.longitude is None:
            place.longitude = ""
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_auto_20210525_2155"),
    ]

    operations = [
        migrations.RunPython(set_blanke),
    ]
